### ISSUE TITLE
download_data_and_model_weights.sh is empty

### ISSUE THREAD

**Issue by DovahCoding** [lanl/EPBD-BERT#1]
Dear Authors

Your model is truly impressive and groundbreaking. I believe it can significantly aid my work. However, I encountered a small issue while trying to run the model. I notice that this file is empty, and I would like to ask that do you have the plan to update this file? Or is it possible to download the model weights by alternative ways?

Best regards

**Comment by ceodspspectrum** [comment]
We are currently working on finding appropriate channel to upload the model weights and datasets as they are really big. We will update the release once we do that.
